name: 'CIF syntax check'
description: 'Check that all *.cif/*.dic files in the specified directory conform to CIF syntax'
inputs:
    check-directory:
      description: 'Directory to check'
      default: '.'
      
outputs:
        result:
                description: 'Result of syntax check'

runs:
        using: 'docker'
        image: 'Dockerfile'
        args: 
         - ${{ inputs.check-directory }}
